# .github/workflows/main.yml

on: push

jobs:
  backfill-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: bcanseco/github-contribution-graph-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_EMAIL: musaddiqelearning@gmail.com.com # replace me
        MAX_DAYS: 365
        MIN_COMMITS_PER_DAY: 0
        MAX_COMMITS_PER_DAY: 5
